# Generated by Django 5.1.5 on 2025-04-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-time_create'], name='news_news_time_cr_5badca_idx'),
        ),
    ]
