# Generated by Django 5.1.5 on 2025-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик-DRAFT'), (1, 'Опубликовано-PUBLISHED')], default=0),
        ),
    ]
